from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from .database import Base

class User(Base):
    __tablename__ = "telegram_users"

    id = Column(Integer, primary_key=True, index=True)
    telegram_user_id = Column(String(50), unique=True, index=True, nullable=False)
    username = Column(String(100), nullable=True)
    first_name = Column(String(100), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    complaints = relationship("Complaint", back_populates="user")
    media = relationship("UserMedia", back_populates="user")

class Complaint(Base):
    __tablename__ = "complaints"

    id = Column(Integer, primary_key=True, index=True)
    ghmc_id = Column(String(50), unique=True, index=True) # Generated upon successful reporting
    telegram_user_id = Column(String(50), ForeignKey("telegram_users.telegram_user_id"))
    
    category = Column(String(100)) # e.g., Pothole, Garbage
    priority = Column(String(50))  # e.g., High, Medium, Low
    description = Column(Text)
    ai_summary = Column(Text)      # Generated by our local AI
    
    gps_lat = Column(Float, nullable=True)
    gps_lng = Column(Float, nullable=True)
    
    status = Column(String(50), default="Pending") # Pending, In Progress, Resolved
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="complaints")
    media = relationship("UserMedia", back_populates="complaint")

class UserMedia(Base):
    __tablename__ = "user_media"

    id = Column(Integer, primary_key=True, index=True)
    telegram_user_id = Column(String(50), ForeignKey("telegram_users.telegram_user_id"))
    complaint_id = Column(Integer, ForeignKey("complaints.id"), nullable=True)
    
    media_type = Column(String(50)) # "photo", "voice"
    file_path = Column(String(255))
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="media")
    complaint = relationship("Complaint", back_populates="media")
